#!/usr/bin/env python3
"""Synchronize a Terraform repository inventory with repositories owned on GitHub."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ENTRY_RE = re.compile(r'^  "([^"]+)"\s*=\s*(.*)$')
OWNER_RE = re.compile(r'^github_owner\s*=\s*"([^"]+)"\s*$')
ARCHIVED_RE = re.compile(r"(?m)^# BEGIN archived repository: (\d+): ([^\n]+)$")
CORE_RESOURCES = [
    ("github_repository", "repo"),
    ("github_repository_vulnerability_alerts", "alerts"),
    ("github_repository_dependabot_security_updates", "dependabot"),
    ("github_workflow_repository_permissions", "actions"),
]


def parse_inventory(path: Path) -> tuple[list[str], str, dict[str, list[str]], list[str]]:
    lines = path.read_text().splitlines()
    owner = next(
        (match.group(1) for line in lines if (match := OWNER_RE.match(line))),
        None,
    )
    if not owner:
        raise SystemExit(f"Could not find github_owner in {path}")

    try:
        start = next(i for i, line in enumerate(lines) if line.strip() == "repositories = {")
    except StopIteration:
        raise SystemExit(f"Could not find repositories map in {path}")

    end = next((i for i in range(start + 1, len(lines)) if lines[i] == "}"), None)
    if end is None:
        raise SystemExit(f"Could not find end of repositories map in {path}")

    entries: dict[str, list[str]] = {}
    current_key: str | None = None
    for line in lines[start + 1 : end]:
        match = ENTRY_RE.match(line)
        if match:
            current_key = match.group(1)
            if current_key in entries:
                raise SystemExit(f"Duplicate repository entry: {current_key}")
            entries[current_key] = [line]
        elif current_key is not None:
            entries[current_key].append(line)
        elif line.strip():
            raise SystemExit(f"Unexpected content before first repository entry: {line}")

    return lines[: start + 1], owner, entries, lines[end:]


def format_inventory(
    prefix: list[str], entries: dict[str, list[str]], suffix: list[str]
) -> str:
    width = max((len(key) for key in entries), default=0)
    body: list[str] = []
    for key in sorted(entries):
        block = entries[key]
        match = ENTRY_RE.match(block[0])
        if not match:
            raise SystemExit(f"Malformed repository entry: {block[0]}")
        body.append(f'  "{key}"{" " * (width - len(key))} = {match.group(2)}')
        body.extend(block[1:])
    return "\n".join([*prefix, *body, *suffix]) + "\n"


def field(block: list[str], name: str) -> str | None:
    text = "\n".join(block)
    if name in {"name", "observed_visibility"}:
        match = re.search(rf'\b{name}\s*=\s*"([^"]+)"', text)
    else:
        match = re.search(rf"\b{name}\s*=\s*(\d+)", text)
    return match.group(1) if match else None


def set_field(block: list[str], name: str, value: str | int) -> None:
    rendered = json.dumps(value) if isinstance(value, str) else str(value)
    pattern = (
        re.compile(rf'(\b{name}\s*=\s*)"[^"]*"')
        if isinstance(value, str)
        else re.compile(rf"(\b{name}\s*=\s*)\d+")
    )
    for index, line in enumerate(block):
        if pattern.search(line):
            block[index] = pattern.sub(rf"\g<1>{rendered}", line, count=1)
            return

    match = ENTRY_RE.match(block[0])
    if not match:
        raise SystemExit(f"Malformed repository entry: {block[0]}")
    rhs = match.group(2).strip()
    if rhs == "{}":
        block[0] = block[0].replace("{}", f"{{ {name} = {rendered} }}", 1)
    elif rhs.startswith("{") and rhs.endswith("}"):
        pos = block[0].rfind("}")
        block[0] = block[0][:pos].rstrip() + f", {name} = {rendered} " + block[0][pos:]
    elif rhs == "{":
        block.insert(1, f"    {name} = {rendered}")
    else:
        raise SystemExit(f"Cannot add {name} to repository entry: {block[0]}")


def effective_name(key: str, block: list[str]) -> str:
    return field(block, "name") or key


def retired_repositories(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    return {repo_id: key for repo_id, key in ARCHIVED_RE.findall(path.read_text())}


def removed_section(repo_id: str, key: str, public: bool) -> str:
    resources = [*CORE_RESOURCES]
    if public:
        resources.append(("github_repository_ruleset", "branch"))

    blocks = []
    for resource_type, resource_name in resources:
        blocks.append(
            "removed {\n"
            f'  from = {resource_type}.{resource_name}["{key}"]\n\n'
            "  lifecycle {\n"
            "    destroy = false\n"
            "  }\n"
            "}"
        )
    return (
        f"# BEGIN archived repository: {repo_id}: {key}\n"
        + "\n\n".join(blocks)
        + f"\n# END archived repository: {repo_id}: {key}"
    )


def append_removed(path: Path, sections: list[str]) -> None:
    if not sections:
        return
    header = (
        "# Generated by .github/scripts/sync-repositories.py.\n"
        "# Archived repositories are forgotten from Terraform state without modifying GitHub."
    )
    existing = path.read_text().rstrip() if path.exists() else header
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(existing + "\n\n" + "\n\n".join(sections) + "\n")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--tfvars", type=Path, required=True)
    parser.add_argument("--repositories-json", type=Path, required=True)
    parser.add_argument("--removed-file", type=Path, required=True)
    args = parser.parse_args()

    prefix, owner, entries, suffix = parse_inventory(args.tfvars)
    repositories = json.loads(args.repositories_json.read_text())
    if not isinstance(repositories, list):
        raise SystemExit("Repository API payload must be a JSON array")

    repos = [
        repo
        for repo in repositories
        if repo.get("owner", {}).get("login") == owner and "id" in repo
    ]
    if not repos:
        raise SystemExit(f"No repositories owned by {owner} were returned")

    by_id = {str(repo["id"]): repo for repo in repos}
    by_name = {repo["name"]: repo for repo in repos}
    retired = retired_repositories(args.removed_file)

    reactivated = sorted(
        repo["name"]
        for repo_id, repo in by_id.items()
        if repo_id in retired and not repo.get("archived", False)
    )
    if reactivated:
        raise SystemExit(
            "Previously retired repositories became active; restore their tfvars entries "
            "and remove the corresponding removed blocks manually: "
            + ", ".join(reactivated)
        )

    tracked: dict[str, str] = {}
    for key, block in entries.items():
        repo_id = field(block, "github_id")
        name = effective_name(key, block)
        if repo_id is None:
            repo = by_name.get(name)
            if not repo:
                raise SystemExit(
                    f"Cannot initialize GitHub ID because repository is missing from API: {name}"
                )
            repo_id = str(repo["id"])
            set_field(block, "github_id", int(repo_id))
        if repo_id in tracked:
            raise SystemExit(
                f"GitHub repository ID {repo_id} is used by both {tracked[repo_id]} and {key}"
            )
        if repo_id in retired:
            raise SystemExit(
                f"Active tfvars entry {key} is still referenced by an archived-state transition"
            )
        if repo_id not in by_id:
            raise SystemExit(
                f"Refusing to modify repository missing from API response: {name} ({repo_id})"
            )
        tracked[repo_id] = key

    renames: list[str] = []
    retirements: list[str] = []
    removed_sections: list[str] = []

    for repo_id, key in list(tracked.items()):
        block = entries[key]
        repo = by_id[repo_id]
        old_name = effective_name(key, block)
        old_visibility = field(block, "observed_visibility") or repo.get(
            "visibility", "public"
        )
        new_name = repo["name"]
        new_visibility = repo.get("visibility", "public")

        if repo.get("archived", False):
            entries.pop(key)
            removed_sections.append(
                removed_section(repo_id, key, public=old_visibility == "public")
            )
            retirements.append(old_name)
            continue

        if old_name != new_name:
            set_field(block, "name", new_name)
            renames.append(f"{old_name} -> {new_name}")

        set_field(block, "observed_visibility", new_visibility)

    active_ids = {
        repo_id for repo_id, repo in by_id.items() if not repo.get("archived", False)
    }
    known_ids = set(tracked) | set(retired)
    additions = sorted(by_id[repo_id]["name"] for repo_id in active_ids - known_ids)

    used_keys = set(entries) | set(retired.values())
    for name in additions:
        repo = by_name[name]
        repo_id = str(repo["id"])
        if name in used_keys:
            raise SystemExit(
                f"Cannot add {name}: its repository name is already used as a stable "
                "Terraform inventory key"
            )
        entries[name] = [
            f'  "{name}" = {{ github_id = {repo_id}, '
            f'observed_visibility = "{repo.get("visibility", "public")}" }}'
        ]
        used_keys.add(name)

    args.tfvars.write_text(format_inventory(prefix, entries, suffix))
    append_removed(args.removed_file, removed_sections)

    print(f"Added: {', '.join(additions) if additions else 'none'}")
    print(f"Renamed: {', '.join(renames) if renames else 'none'}")
    print(f"Archived: {', '.join(retirements) if retirements else 'none'}")


if __name__ == "__main__":
    main()
