#!/usr/bin/env python3
"""Synchronize a JSON Terraform repository inventory with GitHub."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ARCHIVED_RE = re.compile(r"(?m)^# BEGIN archived repository: (\d+): ([^\n]+)$")
CORE_RESOURCES = [
    ("github_repository", "repo"),
    ("github_repository_vulnerability_alerts", "alerts"),
    ("github_repository_dependabot_security_updates", "dependabot"),
    ("github_workflow_repository_permissions", "actions"),
]


def load_inventory(path: Path) -> tuple[dict[str, object], str, dict[str, dict[str, object]]]:
    inventory = json.loads(path.read_text())
    if not isinstance(inventory, dict):
        raise SystemExit(f"{path} must contain a JSON object")

    owner = inventory.get("github_owner")
    repositories = inventory.get("repositories")
    if not isinstance(owner, str) or not owner:
        raise SystemExit(f"{path} must contain a non-empty github_owner string")
    if not isinstance(repositories, dict):
        raise SystemExit(f"{path} must contain a repositories object")
    if not all(isinstance(key, str) and isinstance(value, dict) for key, value in repositories.items()):
        raise SystemExit("Repository keys must be strings and values must be JSON objects")

    return inventory, owner, repositories


def write_inventory(
    path: Path, inventory: dict[str, object], repositories: dict[str, dict[str, object]]
) -> None:
    inventory["repositories"] = dict(sorted(repositories.items()))
    path.write_text(json.dumps(inventory, indent=2, ensure_ascii=False) + "\n")


def effective_name(key: str, entry: dict[str, object]) -> str:
    name = entry.get("name", key)
    if not isinstance(name, str) or not name:
        raise SystemExit(f"Repository {key} has an invalid name")
    return name


def retired_repositories(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    return {repo_id: key for repo_id, key in ARCHIVED_RE.findall(path.read_text())}


def removed_section(repo_id: str, key: str, public: bool) -> str:
    resources = [*CORE_RESOURCES]
    if public:
        resources.append(("github_repository_ruleset", "branch"))

    blocks = []
    for resource_type, resource_name in resources:
        blocks.append(
            "removed {\n"
            f'  from = {resource_type}.{resource_name}["{key}"]\n\n'
            "  lifecycle {\n"
            "    destroy = false\n"
            "  }\n"
            "}"
        )
    return (
        f"# BEGIN archived repository: {repo_id}: {key}\n"
        + "\n\n".join(blocks)
        + f"\n# END archived repository: {repo_id}: {key}"
    )


def append_removed(path: Path, sections: list[str]) -> None:
    if not sections:
        return
    header = (
        "# Generated by .github/scripts/sync-repositories.py.\n"
        "# Archived repositories are forgotten from Terraform state without modifying GitHub."
    )
    existing = path.read_text().rstrip() if path.exists() else header
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(existing + "\n\n" + "\n\n".join(sections) + "\n")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--tfvars", type=Path, required=True)
    parser.add_argument("--repositories-json", type=Path, required=True)
    parser.add_argument("--removed-file", type=Path, required=True)
    args = parser.parse_args()

    inventory, owner, entries = load_inventory(args.tfvars)
    repositories = json.loads(args.repositories_json.read_text())
    if not isinstance(repositories, list):
        raise SystemExit("Repository API payload must be a JSON array")

    repos = [
        repo
        for repo in repositories
        if repo.get("owner", {}).get("login") == owner and "id" in repo
    ]
    if not repos:
        raise SystemExit(f"No repositories owned by {owner} were returned")

    by_id = {str(repo["id"]): repo for repo in repos}
    by_name = {repo["name"]: repo for repo in repos}
    retired = retired_repositories(args.removed_file)

    reactivated = sorted(
        repo["name"]
        for repo_id, repo in by_id.items()
        if repo_id in retired and not repo.get("archived", False)
    )
    if reactivated:
        raise SystemExit(
            "Previously retired repositories became active; restore their tfvars entries "
            "and remove the corresponding removed blocks manually: "
            + ", ".join(reactivated)
        )

    tracked: dict[str, str] = {}
    for key, entry in entries.items():
        name = effective_name(key, entry)
        repo_id_value = entry.get("github_id")
        if repo_id_value is None:
            repo = by_name.get(name)
            if not repo:
                raise SystemExit(
                    f"Cannot initialize GitHub ID because repository is missing from API: {name}"
                )
            repo_id_value = repo["id"]
            entry["github_id"] = repo_id_value
        if not isinstance(repo_id_value, int) or isinstance(repo_id_value, bool):
            raise SystemExit(f"Repository {key} has an invalid github_id")
        repo_id = str(repo_id_value)
        if repo_id in tracked:
            raise SystemExit(
                f"GitHub repository ID {repo_id} is used by both {tracked[repo_id]} and {key}"
            )
        if repo_id in retired:
            raise SystemExit(
                f"Active tfvars entry {key} is still referenced by an archived-state transition"
            )
        if repo_id not in by_id:
            raise SystemExit(
                f"Refusing to modify repository missing from API response: {name} ({repo_id})"
            )
        tracked[repo_id] = key

    renames: list[str] = []
    retirements: list[str] = []
    removed_sections: list[str] = []

    for repo_id, key in list(tracked.items()):
        entry = entries[key]
        repo = by_id[repo_id]
        old_name = effective_name(key, entry)
        old_visibility = entry.get("observed_visibility", repo.get("visibility", "public"))
        new_name = repo["name"]
        new_visibility = repo.get("visibility", "public")

        if repo.get("archived", False):
            entries.pop(key)
            removed_sections.append(
                removed_section(repo_id, key, public=old_visibility == "public")
            )
            retirements.append(old_name)
            continue

        if old_name != new_name:
            if new_name == key:
                entry.pop("name", None)
            else:
                entry["name"] = new_name
            renames.append(f"{old_name} -> {new_name}")

        entry["observed_visibility"] = new_visibility

    active_ids = {
        repo_id for repo_id, repo in by_id.items() if not repo.get("archived", False)
    }
    known_ids = set(tracked) | set(retired)
    additions = sorted(by_id[repo_id]["name"] for repo_id in active_ids - known_ids)

    used_keys = set(entries) | set(retired.values())
    for name in additions:
        repo = by_name[name]
        if name in used_keys:
            raise SystemExit(
                f"Cannot add {name}: its repository name is already used as a stable "
                "Terraform inventory key"
            )
        entries[name] = {
            "github_id": repo["id"],
            "observed_visibility": repo.get("visibility", "public"),
        }
        used_keys.add(name)

    write_inventory(args.tfvars, inventory, entries)
    append_removed(args.removed_file, removed_sections)

    print(f"Added: {', '.join(additions) if additions else 'none'}")
    print(f"Renamed: {', '.join(renames) if renames else 'none'}")
    print(f"Archived: {', '.join(retirements) if retirements else 'none'}")


if __name__ == "__main__":
    main()
