#!/usr/bin/env python3
"""Synchronize envs/dceoy.tfvars with active repositories owned by a GitHub user."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ENTRY_RE = re.compile(r'^  "([^"]+)"\s*=\s*(.*)$')
OWNER_RE = re.compile(r'^github_owner\s*=\s*"([^"]+)"\s*$')
SECTION_RE = re.compile(
    r"(?ms)^# BEGIN archived repository: ([^\n]+)\n.*?^# END archived repository: \1\n?"
)


def parse_inventory(path: Path) -> tuple[list[str], str, dict[str, list[str]], list[str]]:
    lines = path.read_text().splitlines()
    owner = next(
        (match.group(1) for line in lines if (match := OWNER_RE.match(line))),
        None,
    )
    if not owner:
        raise SystemExit(f"Could not find github_owner in {path}")

    try:
        start = next(i for i, line in enumerate(lines) if line.strip() == "repositories = {")
    except StopIteration:
        raise SystemExit(f"Could not find repositories map in {path}")

    end = next(
        (i for i in range(start + 1, len(lines)) if lines[i] == "}"),
        None,
    )
    if end is None:
        raise SystemExit(f"Could not find end of repositories map in {path}")

    prefix = lines[: start + 1]
    suffix = lines[end:]
    entries: dict[str, list[str]] = {}
    current_name: str | None = None

    for line in lines[start + 1 : end]:
        match = ENTRY_RE.match(line)
        if match:
            current_name = match.group(1)
            if current_name in entries:
                raise SystemExit(f"Duplicate repository entry: {current_name}")
            entries[current_name] = [line]
        elif current_name is not None:
            entries[current_name].append(line)
        elif line.strip():
            raise SystemExit(f"Unexpected content before first repository entry: {line}")

    return prefix, owner, entries, suffix


def format_inventory(
    prefix: list[str], entries: dict[str, list[str]], suffix: list[str]
) -> str:
    width = max((len(name) for name in entries), default=0)
    body: list[str] = []
    for name in sorted(entries):
        block = entries[name]
        match = ENTRY_RE.match(block[0])
        if not match:
            raise SystemExit(f"Malformed repository entry: {block[0]}")
        rhs = match.group(2)
        body.append(f'  "{name}"{" " * (width - len(name))} = {rhs}')
        body.extend(block[1:])
    return "\n".join([*prefix, *body, *suffix]) + "\n"


def parse_retired_sections(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    text = path.read_text()
    return {
        match.group(1): match.group(0).rstrip() + "\n"
        for match in SECTION_RE.finditer(text)
    }


def retired_section(name: str, public: bool) -> str:
    resources = [
        ("github_repository", "repo"),
        ("github_repository_vulnerability_alerts", "alerts"),
        ("github_repository_dependabot_security_updates", "dependabot"),
        ("github_workflow_repository_permissions", "actions"),
    ]
    if public:
        resources.append(("github_repository_ruleset", "branch"))

    blocks = []
    for resource_type, resource_name in resources:
        blocks.append(
            "removed {\n"
            f'  from = {resource_type}.{resource_name}["{name}"]\n\n'
            "  lifecycle {\n"
            "    destroy = false\n"
            "  }\n"
            "}"
        )

    return (
        f"# BEGIN archived repository: {name}\n"
        + "\n\n".join(blocks)
        + f"\n# END archived repository: {name}\n"
    )


def write_retired(path: Path, sections: dict[str, str]) -> None:
    if not sections:
        path.unlink(missing_ok=True)
        return

    header = (
        "# Generated by .github/scripts/sync-repositories.py.\n"
        "# Archived repositories are forgotten from Terraform state without modifying GitHub.\n\n"
    )
    text = header + "\n".join(sections[name].rstrip() for name in sorted(sections)) + "\n"
    path.write_text(text)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--tfvars", type=Path, required=True)
    parser.add_argument("--repositories-json", type=Path, required=True)
    parser.add_argument("--removed-file", type=Path, required=True)
    args = parser.parse_args()

    prefix, owner, entries, suffix = parse_inventory(args.tfvars)
    repositories = json.loads(args.repositories_json.read_text())
    if not isinstance(repositories, list):
        raise SystemExit("Repository API payload must be a JSON array")

    by_name = {
        repo["name"]: repo
        for repo in repositories
        if repo.get("owner", {}).get("login") == owner
    }
    if not by_name:
        raise SystemExit(f"No repositories owned by {owner} were returned")

    current = set(entries)
    visible = set(by_name)
    missing = sorted(current - visible)
    if missing:
        raise SystemExit(
            "Refusing to remove repositories missing from the API response: "
            + ", ".join(missing)
        )

    active = {name for name, repo in by_name.items() if not repo.get("archived", False)}
    archived = visible - active
    additions = sorted(active - current)
    retirements = sorted(current & archived)

    sections = parse_retired_sections(args.removed_file)
    reactivated = sorted(set(sections) & active)
    if reactivated:
        raise SystemExit(
            "Previously retired repositories became active; restore their inventory "
            "settings manually before removing the generated removed blocks: "
            + ", ".join(reactivated)
        )

    for name in retirements:
        sections[name] = retired_section(
            name,
            public=by_name[name].get("visibility") == "public",
        )

    for name in retirements:
        entries.pop(name)
    for name in additions:
        entries[name] = [f'  "{name}" = {{}}']

    args.tfvars.write_text(format_inventory(prefix, entries, suffix))
    args.removed_file.parent.mkdir(parents=True, exist_ok=True)
    write_retired(args.removed_file, sections)

    print(f"Added: {', '.join(additions) if additions else 'none'}")
    print(f"Archived: {', '.join(retirements) if retirements else 'none'}")
    print("Reactivated: none")


if __name__ == "__main__":
    main()
